VASM_HOME ?= /opt/vasm
VASM       = $(VASM_HOME)/bin/vasmm68k_mot

ifeq ($(V),1)
  Q =
  DEFINITIONS +=
else
  Q = @
  DEFINITIONS += -quiet
endif

VASMFLAGS  = -Fhunkexe -nosym $(DEFINITIONS)

PLIB_MAJOR = 2
PLIB_MINOR = 0
PLIB_VERSION_SUFFIX = -dev
PLIB_DATE  = 22.06.2026
PLIB_VERSION = $(PLIB_MAJOR).$(PLIB_MINOR)$(PLIB_VERSION_SUFFIX)

SRC        = src
LIB_SOURCE = $(SRC)/ptable_lib.s
LIB_DEPS   = $(SRC)/ptable_boot.s $(SRC)/ptable_fs.s $(SRC)/ptable_hunk.s \
             $(SRC)/ptable_partres.s $(SRC)/parts.s $(SRC)/parts.i \
             $(SRC)/ptable_pub.i $(SRC)/ptable_dosdiag.i \
             $(SRC)/umul32.i $(SRC)/log2.i $(SRC)/raw_debug.i
VERSION_INC = $(SRC)/ptable_version.i

CPU_68020 = -m68020 -D__68020__=1
CPU_68000 = -m68000
DBG_full  = -DDEBUG=1
DBG_small =

FLAVORS = full/68020 full/68000 small/68020 small/68000
TARGETS = $(foreach f,$(FLAVORS),dist/$(f)/ptable.library)

.PHONY: all clean
all: $(TARGETS) dist/ptable.version

$(VERSION_INC):
	$(Q)echo "  VERSION ptable.library $(PLIB_VERSION)"
	$(Q)echo "; Auto-generated by Makefile" > $@
	$(Q)echo "LIB_VERSION	= $(PLIB_MAJOR)" >> $@
	$(Q)echo "LIB_REVISION	= $(PLIB_MINOR)" >> $@
	$(Q)echo "LIB_VERSION_STRING	macro" >> $@
	$(Q)echo "	ifd	__68020__" >> $@
	$(Q)echo "	dc.b	\"ptable.library $(PLIB_VERSION) ($(PLIB_DATE)) [68020]\"" >> $@
	$(Q)echo "	else" >> $@
	$(Q)echo "	dc.b	\"ptable.library $(PLIB_VERSION) ($(PLIB_DATE)) [68000]\"" >> $@
	$(Q)echo "	endc" >> $@
	$(Q)echo "	endm" >> $@

$(TARGETS): dist/%/ptable.library: $(LIB_SOURCE) $(LIB_DEPS) $(VERSION_INC)
	$(eval flav := $(word 1,$(subst /, ,$*)))
	$(eval cpu  := $(word 2,$(subst /, ,$*)))
	$(Q)mkdir -p $(@D)
	$(Q)echo "  VASM    $@ [$(flav), $(cpu)]"
	$(Q)$(VASM) $(VASMFLAGS) $(CPU_$(cpu)) $(DBG_$(flav)) -I $(SRC) -o $@ $(LIB_SOURCE)
	$(Q)echo "          $$(stat -c%s $@) bytes, md5:$$(md5sum $@ | cut -c1-8)"

dist/ptable.version: $(VERSION_INC)
	$(Q)mkdir -p dist
	$(Q)echo "$(PLIB_VERSION) $(PLIB_DATE)" > $@

clean:
	$(Q)rm -rf dist $(VERSION_INC)
