; Auto-generated by Makefile
LIB_VERSION	= 2
LIB_REVISION	= 2
LIB_VERSION_STRING	macro
	ifd	__68020__
	dc.b	"ptable.library 2.2 (03.10.2026) [68020]"
	else
	dc.b	"ptable.library 2.2 (03.10.2026) [68000]"
	endc
	endm
