; Auto-generated by Makefile
LIB_VERSION	= 2
LIB_REVISION	= 1
LIB_VERSION_STRING	macro
	ifd	__68020__
	dc.b	"ptable.library 2.1-dev (23.09.2026) [68020]"
	else
	dc.b	"ptable.library 2.1-dev (23.09.2026) [68000]"
	endc
	endm
